import { StyleSheet } from 'react-native';
import { COLORS } from '../../../../shared/theme/colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc', // Fondo más suave y moderno
  },
  scrollContent: {
    flexGrow: 1,
    padding: 20,
    paddingBottom: 150, // Espacio adicional para los botones fijos
  },
  section: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 24,
    marginBottom: 20,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: COLORS.gray700,
    marginBottom: 24,
    textAlign: 'left',
    letterSpacing: 0.2,
  },
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 15,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  input: {
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderRadius: 14,
    padding: 16,
    fontSize: 16,
    color: COLORS.gray700,
    backgroundColor: COLORS.white,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    minHeight: 52,
  },
  inputFocused: {
    borderColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.15,
  },
  pickerContainer: {
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderRadius: 14,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  pickerText: {
    fontSize: 16,
    color: COLORS.gray700,
    flex: 1,
  },
  buttonContainer: {
    position: 'absolute',
    bottom: 80, // Aproximadamente la altura del menú inferior
    left: 0,
    right: 0,
    backgroundColor: '#f8fafc',
    padding: 24,
    paddingTop: 18,
    paddingBottom: 28,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 16,
  },
  buttonSpacer: {
    width: 16,
  },
  cancelButton: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#d1d5db',
    backgroundColor: '#f9fafb',
  },
  cancelButtonText: {
    color: '#4b5563',
    fontSize: 16,
    fontWeight: '600',
  },
  saveButton: {
    flex: 1,
    borderRadius: 14,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 22,
    padding: 28,
    width: '92%',
    maxWidth: 440,
    elevation: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.25,
    shadowRadius: 24,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.gray700,
    marginBottom: 14,
    textAlign: 'center',
  },
  modalMessage: {
    fontSize: 16,
    color: '#6b7280',
    marginBottom: 28,
    textAlign: 'center',
    lineHeight: 24,
  },
  modalButtonRow: {
    flexDirection: 'row',
    gap: 16,
  },
  modalButtonSpacer: {
    width: 16,
  },
  modalButton: {
    flex: 1,
    borderRadius: 14,
  },
  pickerModalContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 18,
    maxHeight: 320,
    marginHorizontal: 20,
    marginBottom: 50,
    marginTop: 'auto',
    elevation: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
  },
  pickerModalTitle: {
    fontSize: 19,
    fontWeight: '600',
    color: COLORS.gray700,
    paddingVertical: 20,
    paddingHorizontal: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    textAlign: 'center',
    backgroundColor: '#f9fafb',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
  },
  pickerOption: {
    paddingVertical: 20,
    paddingHorizontal: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  pickerOptionText: {
    fontSize: 17,
    color: COLORS.gray700,
    textAlign: 'center',
  },
  requiredIndicator: {
    color: '#ef4444',
    marginLeft: 4,
    fontSize: 15,
    fontWeight: '600',
  },
});

export default styles;